### PR TITLE
* Swapped out WatchService with the library directory-watcher, which …

### PR DESCRIPTION
**Pull request by twadzins**
…uses java's WatchService for all but MacOS.

* Added libraries to allow the project to compile
* Added directory-watcher-0.18.0.jar and 3 dependent jars
* Updated artifact building to include the contents of directory-watcher-0.18.0.jar and dependent jars into the final artifact jar.

### CODE REVIEW

**Comment by twadzins** [comment]
I am only able to test this out on MacOS. According to the Directory Watcher docs (https://github.com/gmethvin/directory-watcher), for windows and linux, Directory Watcher just uses WatchService so hopefully all will work as before for windows and linux.

**Comment by csabagabor** [comment]
Hi Tom,

Thank you very much for the changes. I tested the changes on Windows, Mac and Linux. There is one thing I needed to change (to use a timestamp based hash algorithm for `DirectoryWatcher` otherwise, the test would run twice on Windows (file updation event is sent twice). I hope this hash will be good enough. Other than that, looks good so I will merge your changes, push the aforementioned change along with the version update as well, and will upload the new version to the Jerbrains repository as well. Thanks again!

**Comment by twadzins** [comment]
Hey Csaba,
Great news that it works in your tests (with the hash fix). I was looking
for the hash fix in the source but didn't see it there yet. Maybe I missed
it or you haven't pushed it? I would guess that it would be setting
directory watcher's fileHashing(false) to fileHashing(true), and then (to
allow the same test to be run over and over) always randomizing/"making
unique" something in the contents of default.txt during a new run so that
the file hash changes even when the test params don't change.

Something else that I was wondering about:
I tried it with DCEVM (using the JetBrains JBR Java runtime (which includes
DCEVM) and it works great. I'm pretty sure from the various DCEVM docs that
it can only be used in Debug mode, not Run mode.  However, the keep junit
running docs suggests (in the screenshot image on the plugin page) that you
can use DCEVM in run mode. I would guess that run mode only works for
JRebel which if I recall correctly allows updates even in run mode. Does
this differ from what you have been able to do (i.e. have you updated code
and had a new test kick off in Run mode with DCEVM and seen the test run
with the updated change?)

Also, I could never get run mode to actually "stay alive" (The test just
runs once and ends). It looks like (and maybe this is with more recent
IntelliJ versions, not sure), even in the run mode, doExecuteAsync() is
called, but CustomRunner seems to expect that doExecute() will be called.

**Comment by csabagabor** [comment]
Hi Tom,

I've just merged the changes for the hash change. 
Regarding Run mode, I am going to check it.
I think DCEVM should work in Run mode as well, as it is relying on some JVM trickery to do the hotswap, it does not need any functionality which comes from the Java debug agent. Will try it when I have time!

**Comment by csabagabor** [comment]
Hi again, Tom,

You are right regarding Run mode. It looks like I forgot to add doExecuteAsync(). I will provide a fix in version 1.3.
Regarding DCEVM, I just tried it and it works in Run mode. According to http://hotswapagent.org/mydoc_configuration.html you need to create a file called `hotswap-agent.properties` under src/main/resources with the setting `autoHotswap=true`. It also says to set the `extraClasspath` property, but that was not needed in my case. I will mention this in the plugin's documentation though!

**Comment by twadzins** [comment]
>Regarding DCEVM, I just tried it and it works in Run mode.

Ah, thanks! I had just been using the JetBrains runtime with DCEVM and no hotswap-agent.jar, and with that, debug mode works, but not run mode. After trying it with hotswap-agent.jar and `autoHotswap=true` like you suggested, run mode changes worked.

I did notice that with run mode there would sometimes be a timing issue: the default.txt change would sometimes get detected before the hotswap agent and so the test gets run rerun without the class change. Have you run into this?

I guess the code could have a delay after file detection, but a problem with that is it a) adds a delay every time (which hurts the user experience, since the user is using this tool to be super fast), and it's hard to know what the right amount of delay should be so that the compile always happens. Ideally, there would be some hook to detect when the hotswap agent is active with autoHotswap and a hotswap has occurred. It doesn't seem clear how that might be done. Because of that a delay might be the only way to attempt to avoid some/most of the timing issues.

If you think that adding a delay is the way to go, it would be nice if it is only added for the run mode, since this timing issue doesn't occur (at least for me so far) with regular debug mode hotswapping (with or without DCEVM). That way debug mode can be ultra fast to trigger the next test. Note that I generally always us debug mode (with DCEVM) for using "keep junit running" anyway, since it's easier to setup compared with run mode - no java arguments are needed to be added to each run and no hotswap agent jar is needed. That makes me particularly eager to not have it have any additional delays in debug mode, even if it is something like 50ms.

**Comment by csabagabor** [comment]
Hi again, Tom,

On windows, I haven't really experienced this issue. As a workaround, the
classes can be manually reloaded before running the test again
by rebuilding the project or pressing the 'Compile and reload file'
 option in IntelliJ. For now, I will leave version 1.3 as it is and upload
it to Jetbrains.

**Comment by twadzins** [comment]
Sounds great. When I have some time, I'll look into reproducing the issue and seeing if I can come up with any fix.

> Hi again, Tom, On windows, I haven't really experienced this issue. As a workaround, the classes can be manually reloaded before running the test again by rebuilding the project or pressing the 'Compile and reload file' option in IntelliJ. For now, I will leave version 1.3 as it is and upload it to Jetbrains.
> […](#)

**Pull request merged**
